### ISSUE TITLE
Can you share the dataloader and FusionHead of your code?

### ISSUE THREAD

**Issue by 1362303119** [ydk122024/MCDA#1]
Hello, I'm having trouble reproducing your code, can you share your full code?

**Comment by 1362303119** [comment]
My email is zhanglili_955@163.com, thank you very much!

**Comment by ydk122024** [comment]
Thank you for your attention. We plan to share all codes once the manuscript is reviewed.

**Comment by 1362303119** [comment]
I'm sorry, I'm a first-year graduate student and I'm having trouble getting started with medical image processing, can you just share the dataloader? I promise it's just for learning. Thank you very much！
